// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCop-EmFBWtt4PV-WtBDdGqvgR0B_2HkA8',
    appId: '1:241739587:web:d612c95eb43fe1e5ddb1f6',
    messagingSenderId: '241739587',
    projectId: 'chessgameauth',
    authDomain: 'chessgameauth.firebaseapp.com',
    storageBucket: 'chessgameauth.firebasestorage.app',
    measurementId: 'G-FL407MT0Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDREnaS9jLF51ub_IkNVWhm0dqekpLXTvc',
    appId: '1:241739587:android:155567470271b255ddb1f6',
    messagingSenderId: '241739587',
    projectId: 'chessgameauth',
    storageBucket: 'chessgameauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFH6aus50LCo8WP-AaDt_IOnWx6XCcJm8',
    appId: '1:241739587:ios:c74640362ef65369ddb1f6',
    messagingSenderId: '241739587',
    projectId: 'chessgameauth',
    storageBucket: 'chessgameauth.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFH6aus50LCo8WP-AaDt_IOnWx6XCcJm8',
    appId: '1:241739587:ios:c74640362ef65369ddb1f6',
    messagingSenderId: '241739587',
    projectId: 'chessgameauth',
    storageBucket: 'chessgameauth.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCop-EmFBWtt4PV-WtBDdGqvgR0B_2HkA8',
    appId: '1:241739587:web:1d6728fe4adb06ecddb1f6',
    messagingSenderId: '241739587',
    projectId: 'chessgameauth',
    authDomain: 'chessgameauth.firebaseapp.com',
    storageBucket: 'chessgameauth.firebasestorage.app',
    measurementId: 'G-4GLP9ZN1BB',
  );
}
